sentinel.settings:
  type: config_object
  label: 'Sentinel Key Settings'
  mapping:
    whitelist_ips:
      type: sequence
      label: 'Whitelisted IP Addresses'
      sequence:
        type: string
    blacklist_ips:
      type: sequence
      label: 'Blacklisted IP Addresses'
      sequence:
        type: string
    custom_auth_header:
      type: string
      label: 'Custom Authentication Header'
    allowed_paths:
      type: sequence
      label: 'Allowed API Paths'
      sequence:
        type: string
    failure_limit:
      type: integer
      label: 'Max Failed Attempts Before Block'
    failure_limit_time:
      type: string
      label: 'Failure Limit Time Period'
    max_rate_limit:
      type: integer
      label: 'Max Requests Allowed'
    max_rate_limit_time:
      type: string
      label: 'Rate Limit Time Period'
    encryption_key:
      type: string
      label: 'Secret Key'
    encryption_key_hash:
      type: string
      label: 'Secret Key Hash'
    auto_generate:
      type: boolean
      label: 'Auto-Generate API keys'
    auto_generate_roles:
      type: sequence
      label: 'Roles to Auto-Generate'
      sequence:
        type: string
    auto_generate_duration:
      type: int
      label: 'Auto-Generate Duration'
    auto_generate_duration_unit:
      type: int
      label: 'Auto-Generate Duration Unit'

entity_reference_selection.sentinel_key_user_selection:
  type: entity_reference_selection.default:user
  label: 'Unique User Selection handler settings'
